// // Copyright 2015 The go-ethereum Authors
// // This file is part of the go-ethereum library.
// //
// // The go-ethereum library is free software: you can redistribute it and/or modify
// // it under the terms of the GNU Lesser General Public License as published by
// // the Free Software Foundation, either version 3 of the License, or
// // (at your option) any later version.
// //
// // The go-ethereum library is distributed in the hope that it will be useful,
// // but WITHOUT ANY WARRANTY; without even the implied warranty of
// // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// // GNU Lesser General Public License for more details.
// //
// // You should have received a copy of the GNU Lesser General Public License
// // along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

// package Firewall

// import (
// 	"errors"
// 	"fmt"
// 	"math/big"
// 	"sync/atomic"

// 	"github.com/ethereum/go-ethereum/common"
// 	"github.com/ethereum/go-ethereum/common/hexutil"
// 	"github.com/ethereum/go-ethereum/consensus/misc/eip4844"
// 	"github.com/ethereum/go-ethereum/core"
// 	"github.com/ethereum/go-ethereum/core/firewall"
// 	"github.com/ethereum/go-ethereum/core/state"
// 	"github.com/ethereum/go-ethereum/core/stateless"
// 	"github.com/ethereum/go-ethereum/core/txpool"
// 	"github.com/ethereum/go-ethereum/core/types"
// 	"github.com/ethereum/go-ethereum/core/vm"
// 	"github.com/ethereum/go-ethereum/internal/ethapi"
// 	"github.com/ethereum/go-ethereum/log"
// 	"github.com/ethereum/go-ethereum/miner/minertracer"
// 	"github.com/ethereum/go-ethereum/params"
// 	"github.com/holiman/uint256"
// )

// var (
// 	errBlockInterruptedByNewHead  = errors.New("new head arrived while building block")
// 	errBlockInterruptedByRecommit = errors.New("recommit interrupt while building block")
// 	errBlockInterruptedByTimeout  = errors.New("timeout while building block")
// )

// // environment is the worker's current environment and holds all
// // information of the sealing block generation.
// type environment struct {
// 	signer   types.Signer
// 	state    *state.StateDB // apply state changes here
// 	tcount   int            // tx count in cycle
// 	gasPool  *core.GasPool  // available gas used to pack transactions
// 	coinbase common.Address
// 	evm      *vm.EVM

// 	header   *types.Header
// 	txs      []*types.Transaction
// 	receipts []*types.Receipt
// 	sidecars []*types.BlobTxSidecar
// 	blobs    int

// 	witness *stateless.Witness
// }

// const (
// 	commitInterruptNone int32 = iota
// 	commitInterruptNewHead
// 	commitInterruptResubmit
// 	commitInterruptTimeout
// )

// // newPayloadResult is the result of payload generation.
// type newPayloadResult struct {
// 	err      error
// 	block    *types.Block
// 	fees     *big.Int               // total block fees
// 	sidecars []*types.BlobTxSidecar // collected blobs of blob transactions
// 	stateDB  *state.StateDB         // StateDB after executing the transactions
// 	receipts []*types.Receipt       // Receipts collected during construction
// 	requests [][]byte               // Consensus layer requests collected during block construction
// 	witness  *stateless.Witness     // Witness is an optional stateless proof
// }

// // generateParams wraps various settings for generating sealing task.
// type generateParams struct {
// 	timestamp   uint64            // The timestamp for sealing task
// 	forceTime   bool              // Flag whether the given timestamp is immutable or not
// 	parentHash  common.Hash       // Parent block hash, empty means the latest chain head
// 	coinbase    common.Address    // The fee recipient address for including transaction
// 	random      common.Hash       // The randomness generated by beacon chain, empty before the merge
// 	withdrawals types.Withdrawals // List of withdrawals to include in block (shanghai field)
// 	beaconRoot  *common.Hash      // The beacon root (cancun field).
// 	noTxs       bool              // Flag whether an empty block without any transaction is expected
// }

// func (miner *Miner) runIntentGuardProtection(env *environment, tx *types.Transaction) (bool, string) {
// 	if miner.txSimulationPool.IsUserSimulated(tx.Hash()) {
// 		log.Info("Transaction is user simulated, runnning block simulation", "hash", tx.Hash())
// 		simResult, err := miner.simulateTxInBlockContext(env, tx)

// 		// compare simulations
// 		safeResult, err := miner.txSimulationPool.IsTransactionSafe(tx.Hash(), simResult.FTE)
// 		if err != nil {
// 			return false, "IntentGuard: error comparing simulations"
// 		}
// 		if !safeResult.Match {
// 			return true, "IntentGuard detected changes in the transaction outcome, protecting user against malicious behavior"
// 		}
// 	}
// 	return false, ""
// }

// // simulateTxInBlockContext performs a pure, isolated simulation of a single transaction.
// // It uses a copy of the state and a custom tracer to capture detailed execution data,
// // such as balance transfers (fullTxEvents), without modifying the actual world state.
// func (miner *Miner) simulateTxInBlockContext(env *environment, tx *types.Transaction) (*state.SimCallResult, error) {
// 	// 1. Create a safe, isolated copy of the state so the original is not modified.
// 	simState := env.state.Copy()

// 	// 2. Setup the tracer to capture the events we need (e.g., balance transfers).
// 	tracer := minertracer.NewMinerEventTracer(env.header.Number.Uint64())
// 	tracer.Reset(tx.Hash(), uint(len(env.txs))) // tx index is the next one in the block
// 	vmConfig := vm.Config{
// 		Tracer:    tracer.GetHooks(),
// 		NoBaseFee: true, // In the miner, we handle gas price checks ourselves.
// 	}

// 	// 3. Prepare the EVM environment for the single transaction execution.
// 	blockCtx := core.NewEVMBlockContext(env.header, miner.chain, &env.coinbase)
// 	// We use a hooked stateDB to route state accesses to the tracer.
// 	hookedState := state.NewHookedState(simState, tracer.GetHooks())
// 	evm := vm.NewEVM(blockCtx, hookedState, miner.chainConfig, vmConfig)

// 	// 4. Execute the transaction.
// 	// We use ApplyMessage directly, as it's the core execution logic used by simulations.
// 	simState.SetTxContext(tx.Hash(), len(env.txs))
// 	msg, err := core.TransactionToMessage(tx, env.signer, env.header.BaseFee)
// 	if err != nil {
// 		return nil, err
// 	}
// 	result, err := core.ApplyMessage(evm, msg, new(core.GasPool).AddGas(msg.GasLimit), tx.Hash())
// 	if err != nil {
// 		return nil, err
// 	}

// 	// 5. Package the results into the desired SimCallResult structure.
// 	callRes := &state.SimCallResult{
// 		ReturnValue: result.Return(),
// 		Logs:        simState.Logs(),
// 		FTE:         tracer.FullTxEvents,
// 		GasUsed:     hexutil.Uint64(result.UsedGas),
// 	}
// 	if result.Failed() {
// 		callRes.Status = hexutil.Uint64(types.ReceiptStatusFailed)
// 		if errors.Is(result.Err, vm.ErrExecutionReverted) {
// 			revertErr := ethapi.NewRevertError(result.Revert())
// 			callRes.Error = &state.CallError{Message: revertErr.Error(), Code: errCodeReverted, Data: revertErr.ErrorData().(string)}
// 		} else {
// 			callRes.Error = &state.CallError{Message: result.Err.Error(), Code: errCodeVMError, Data: result.Err.Error()}
// 		}
// 	} else {
// 		callRes.Status = hexutil.Uint64(types.ReceiptStatusSuccessful)
// 	}

// 	return callRes, nil
// }

// // applyTransaction runs the transaction. If execution fails, state and gas pool are reverted.
// func (miner *Miner) applyTransaction(env *environment, tx *types.Transaction) (*types.Receipt, error) {
// 	var (
// 		snap = env.state.Snapshot()
// 		gp   = env.gasPool.Gas()
// 	)
// 	receipt, err := core.ApplyTransaction(env.evm, env.gasPool, env.state, env.header, tx, &env.header.GasUsed)
// 	if err != nil {
// 		env.state.RevertToSnapshot(snap)
// 		env.gasPool.SetGas(gp)
// 	}
// 	return receipt, err
// }

// func (miner *Miner) commitTransactions(env *environment, plainTxs, blobTxs *transactionsByPriceAndNonce, interrupt *atomic.Int32) error {
// 	gasLimit := env.header.GasLimit
// 	if env.gasPool == nil {
// 		env.gasPool = new(core.GasPool).AddGas(gasLimit)
// 	}
// 	for {
// 		// Check interruption signal and abort building if it's fired.
// 		if interrupt != nil {
// 			if signal := interrupt.Load(); signal != commitInterruptNone {
// 				return signalToErr(signal)
// 			}
// 		}
// 		// If we don't have enough gas for any further transactions then we're done.
// 		if env.gasPool.Gas() < params.TxGas {
// 			log.Trace("Not enough gas for further transactions", "have", env.gasPool, "want", params.TxGas)
// 			break
// 		}
// 		// If we don't have enough blob space for any further blob transactions,
// 		// skip that list altogether
// 		if !blobTxs.Empty() && env.blobs >= eip4844.MaxBlobsPerBlock(miner.chainConfig, env.header.Time) {
// 			log.Trace("Not enough blob space for further blob transactions")
// 			blobTxs.Clear()
// 			// Fall though to pick up any plain txs
// 		}
// 		// Retrieve the next transaction and abort if all done.
// 		var (
// 			ltx *txpool.LazyTransaction
// 			txs *transactionsByPriceAndNonce
// 		)
// 		pltx, ptip := plainTxs.Peek()
// 		bltx, btip := blobTxs.Peek()

// 		switch {
// 		case pltx == nil:
// 			txs, ltx = blobTxs, bltx
// 		case bltx == nil:
// 			txs, ltx = plainTxs, pltx
// 		default:
// 			if ptip.Lt(btip) {
// 				txs, ltx = blobTxs, bltx
// 			} else {
// 				txs, ltx = plainTxs, pltx
// 			}
// 		}
// 		if ltx == nil {
// 			break
// 		}
// 		// If we don't have enough space for the next transaction, skip the account.
// 		if env.gasPool.Gas() < ltx.Gas {
// 			log.Trace("Not enough gas left for transaction", "hash", ltx.Hash, "left", env.gasPool.Gas(), "needed", ltx.Gas)
// 			txs.Pop()
// 			continue
// 		}

// 		// Most of the blob gas logic here is agnostic as to if the chain supports
// 		// blobs or not, however the max check panics when called on a chain without
// 		// a defined schedule, so we need to verify it's safe to call.
// 		if miner.chainConfig.IsCancun(env.header.Number, env.header.Time) {
// 			left := eip4844.MaxBlobsPerBlock(miner.chainConfig, env.header.Time) - env.blobs
// 			if left < int(ltx.BlobGas/params.BlobTxBlobGasPerBlob) {
// 				log.Trace("Not enough blob space left for transaction", "hash", ltx.Hash, "left", left, "needed", ltx.BlobGas/params.BlobTxBlobGasPerBlob)
// 				txs.Pop()
// 				continue
// 			}
// 		}

// 		// Transaction seems to fit, pull it up from the pool
// 		tx := ltx.Resolve()
// 		if tx == nil {
// 			log.Trace("Ignoring evicted transaction", "hash", ltx.Hash)
// 			txs.Pop()
// 			continue
// 		}

// 		// Error may be ignored here. The error has already been checked
// 		// during transaction acceptance in the transaction pool.
// 		from, _ := types.Sender(env.signer, tx)

// 		// Check whether the tx is replay protected. If we're not in the EIP155 hf
// 		// phase, start ignoring the sender until we do.
// 		if tx.Protected() && !miner.chainConfig.IsEIP155(env.header.Number) {
// 			log.Trace("Ignoring replay protected transaction", "hash", ltx.Hash, "eip155", miner.chainConfig.EIP155Block)
// 			txs.Pop()
// 			continue
// 		}
// 		// Start executing the transaction
// 		env.state.SetTxContext(tx.Hash(), env.tcount)

// 		err := miner.commitTransaction(env, tx)
// 		switch {
// 		case errors.Is(err, core.ErrNonceTooLow):
// 			// New head notification data race between the transaction pool and miner, shift
// 			log.Trace("Skipping transaction with low nonce", "hash", ltx.Hash, "sender", from, "nonce", tx.Nonce())
// 			txs.Shift()

// 		case errors.Is(err, nil):
// 			// Everything ok, collect the logs and shift in the next transaction from the same account
// 			txs.Shift()

// 		default:
// 			// Transaction is regarded as invalid, drop all consecutive transactions from
// 			// the same sender because of `nonce-too-high` clause.
// 			log.Debug("Transaction failed, account skipped", "hash", ltx.Hash, "err", err)
// 			txs.Pop()
// 		}
// 	}
// 	return nil
// }

// // fillTransactions retrieves the pending transactions from the txpool and fills them
// // into the given sealing block. The transaction selection and ordering strategy can
// // be customized with the plugin in the future.
// func (miner *Miner) fillTransactions(interrupt *atomic.Int32, env *environment) error {
// 	miner.confMu.RLock()
// 	tip := miner.config.GasPrice
// 	prio := miner.prio
// 	miner.confMu.RUnlock()

// 	// Retrieve the pending transactions pre-filtered by the 1559/4844 dynamic fees
// 	filter := txpool.PendingFilter{
// 		MinTip: uint256.MustFromBig(tip),
// 	}
// 	if env.header.BaseFee != nil {
// 		filter.BaseFee = uint256.MustFromBig(env.header.BaseFee)
// 	}
// 	if env.header.ExcessBlobGas != nil {
// 		filter.BlobFee = uint256.MustFromBig(eip4844.CalcBlobFee(miner.chainConfig, env.header))
// 	}
// 	filter.OnlyPlainTxs, filter.OnlyBlobTxs = true, false
// 	pendingPlainTxs := miner.txpool.Pending(filter)

// 	filter.OnlyPlainTxs, filter.OnlyBlobTxs = false, true
// 	pendingBlobTxs := miner.txpool.Pending(filter)

// 	// Split the pending transactions into locals and remotes.
// 	prioPlainTxs, normalPlainTxs := make(map[common.Address][]*txpool.LazyTransaction), pendingPlainTxs
// 	prioBlobTxs, normalBlobTxs := make(map[common.Address][]*txpool.LazyTransaction), pendingBlobTxs

// 	for _, account := range prio {
// 		if txs := normalPlainTxs[account]; len(txs) > 0 {
// 			delete(normalPlainTxs, account)
// 			prioPlainTxs[account] = txs
// 		}
// 		if txs := normalBlobTxs[account]; len(txs) > 0 {
// 			delete(normalBlobTxs, account)
// 			prioBlobTxs[account] = txs
// 		}
// 	}
// 	// Fill the block with all available pending transactions.
// 	if len(prioPlainTxs) > 0 || len(prioBlobTxs) > 0 {
// 		plainTxs := newTransactionsByPriceAndNonce(env.signer, prioPlainTxs, env.header.BaseFee)
// 		blobTxs := newTransactionsByPriceAndNonce(env.signer, prioBlobTxs, env.header.BaseFee)

// 		if err := miner.commitTransactions(env, plainTxs, blobTxs, interrupt); err != nil {
// 			return err
// 		}
// 	}
// 	if len(normalPlainTxs) > 0 || len(normalBlobTxs) > 0 {
// 		plainTxs := newTransactionsByPriceAndNonce(env.signer, normalPlainTxs, env.header.BaseFee)
// 		blobTxs := newTransactionsByPriceAndNonce(env.signer, normalBlobTxs, env.header.BaseFee)

// 		if err := miner.commitTransactions(env, plainTxs, blobTxs, interrupt); err != nil {
// 			return err
// 		}
// 	}
// 	return nil
// }

// // totalFees computes total consumed miner fees in Wei. Block transactions and receipts have to have the same order.
// func totalFees(block *types.Block, receipts []*types.Receipt) *big.Int {
// 	feesWei := new(big.Int)
// 	for i, tx := range block.Transactions() {
// 		minerFee, _ := tx.EffectiveGasTip(block.BaseFee())
// 		feesWei.Add(feesWei, new(big.Int).Mul(new(big.Int).SetUint64(receipts[i].GasUsed), minerFee))
// 		// TODO (MariusVanDerWijden) add blob fees
// 	}
// 	return feesWei
// }

// // signalToErr converts the interruption signal to a concrete error type for return.
// // The given signal must be a valid interruption signal.
// func signalToErr(signal int32) error {
// 	switch signal {
// 	case commitInterruptNewHead:
// 		return errBlockInterruptedByNewHead
// 	case commitInterruptResubmit:
// 		return errBlockInterruptedByRecommit
// 	case commitInterruptTimeout:
// 		return errBlockInterruptedByTimeout
// 	default:
// 		panic(fmt.Errorf("undefined signal %d", signal))
// 	}
// }

// const (
// 	errCodeNonceTooHigh            = -38011
// 	errCodeNonceTooLow             = -38010
// 	errCodeIntrinsicGas            = -38013
// 	errCodeInsufficientFunds       = -38014
// 	errCodeBlockGasLimitReached    = -38015
// 	errCodeBlockNumberInvalid      = -38020
// 	errCodeBlockTimestampInvalid   = -38021
// 	errCodeSenderIsNotEOA          = -38024
// 	errCodeMaxInitCodeSizeExceeded = -38025
// 	errCodeClientLimitExceeded     = -38026
// 	errCodeInternalError           = -32603
// 	errCodeInvalidParams           = -32602
// 	errCodeReverted                = -32000
// 	errCodeVMError                 = -32015
// )

// // SimulateBlockWithFirewall processes a list of transactions to build a block,
// // validating each transaction against a user-provided simulation if one exists
// // in the provided firewall pool. Transactions that fail validation are dropped
// // from the final block.
// //
// // This function is designed for a special-purpose RPC service and not for live mining.
// func (w *Firewall) SimulateBlockWithFirewall(parent *types.Block, timestamp uint64, txs types.Transactions, blobs []*types.Blob, firewallPool *firewall.TxSimulationPool) (*core.BlockGen, error) {
// 	// 1. Setup the environment for the new block.
// 	config := w.config
// 	chain := w.chain
// 	gasLimit := parent.GasLimit()

// 	header := &types.Header{
// 		ParentHash: parent.Hash(),
// 		Number:     new(big.Int).Add(parent.Number(), common.Big1),
// 		GasLimit:   gasLimit,
// 		Time:       timestamp,
// 		Difficulty: common.Big1, // Not relevant for PoS simulation
// 		BaseFee:    w.calcBaseFee(parent.Header()),
// 	}

// 	statedb, err := chain.StateAt(parent.Root())
// 	if err != nil {
// 		return nil, err
// 	}
// 	blockGen := core.NewBlockGen(header, chain, statedb, &config.Genesis.Config, w.signer)

// 	// 2. Iterate through the predetermined transactions, validating and applying them.
// 	for i, tx := range txs {
// 		txHash := tx.Hash()

// 		// 2a. If the transaction is not protected by the firewall, apply it directly.
// 		if !firewallPool.IsUserSimulated(txHash) {
// 			if err := blockGen.AddTx(tx); err != nil {
// 				log.Warn("Transaction skipped during simulation (not firewall-protected)", "index", i, "hash", txHash, "err", err)
// 			}
// 			continue
// 		}

// 		// 2b. The transaction is protected. We must run a simulation on a temporary
// 		// state and compare the result before applying it to the actual block state.

// 		// Create a tracer to capture the events from our simulation.
// 		tracer := state.NewEventTracer(txHash)
// 		vmConfig := w.evm.Config
// 		vmConfig.Tracer = tracer

// 		// We need to run the transaction on a perfect copy of the current state.
// 		// We can't use the blockGen's main stateDB as that would be a permanent change.
// 		simState := blockGen.State().Copy()

// 		// The gas pool is also stateful, so we need a temporary copy for the simulation.
// 		simGasPool := new(core.GasPool).AddGas(blockGen.GasPool().Gas())
// 		blockUsedGas := blockGen.Header().GasUsed

// 		// Apply the transaction to the temporary state to get the execution events.
// 		if _, err := core.ApplyTransaction(chain.Config(), chain, &w.coinbase, simGasPool, simState, blockGen.Header(), tx, &blockUsedGas, vmConfig); err != nil {
// 			log.Warn("Firewall-protected transaction failed pre-simulation, dropping", "index", i, "hash", txHash, "err", err)
// 			continue // This transaction is invalid anyway, so we drop it.
// 		}

// 		// 2c. Now, compare the result of our simulation with the user's expectation.
// 		blockFTE := tracer.GetEvents()
// 		result, err := firewallPool.IsTransactionSafe(txHash, blockFTE)
// 		if err != nil {
// 			log.Error("Firewall check failed unexpectedly, dropping transaction", "index", i, "hash", txHash, "err", err)
// 			continue
// 		}

// 		// 2d. If the simulation did not match, drop the tx and move to the next.
// 		if !result.Match {
// 			log.Info("Firewall validation failed: simulation mismatch, dropping tx", "index", i, "hash", txHash, "reason", result.Reason)
// 			continue
// 		}

// 		// 2e. The simulation matched! Now we apply the transaction to the real block.
// 		log.Info("Firewall validation successful, including tx in block", "index", i, "hash", txHash)
// 		if err := blockGen.AddTx(tx); err != nil {
// 			// This would be very unusual, as it implies the pre-simulation succeeded
// 			// but the real application failed. It could happen in an extreme edge case.
// 			log.Error("FATAL: Transaction passed firewall but failed final application", "index", i, "hash", txHash, "err", err)
// 		}
// 	}

// 	// 3. Return the BlockGen object containing the final state and list of
// 	// transactions that passed validation. The caller can then build the final block.
// 	return blockGen, nil
// }
